name: d_crypto_lite
description: "A dantown app clone"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  default_ui_components:
    git:
      url: https://github.com/thedevsaxist/default_ui_components
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  provider: ^6.1.5
  uicons: ^1.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/headshot.jpeg
    - .env
