name: dantown_clone
description: "A dantown app clone"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  default_ui_components:
    git:
      url: https://github.com/thedevsaxist/default_ui_components
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  provider: ^6.1.5
  uicons: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/app/core/gen/

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/logos/network providers/
    - assets/images/
    - .env
